services:
    glory_setting.manager:
        class: Glory\SettingBundle\Manager\SettingManager

    glory_setting.twig.extension:
        class: Glory\SettingBundle\Twig\Extension\SettingsExtension
        arguments: [@glory_setting.manager]
        tags:
            - { name: twig.extension }
