services:
    glory_setting.manager:
        class: Glory\Bundle\SettingBundle\Manager\SettingManager

    glory_setting.twig.extension:
        class: Glory\Bundle\SettingBundle\Twig\Extension\SettingsExtension
        arguments: [@glory_setting.manager]
        tags:
            - { name: twig.extension }
    
    glory_setting.form.setting:
        class: Glory\Bundle\SettingBundle\Form\Type\SettingType
        tags: 
            - {name:form.type, alias:glory_setting}
